apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: studyimg-node
  name: studyimg-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: studyimg-node
    spec:
      containers:
        - image: gcr.io/studyenv4/hello_img:v1
          name: studyimg-node
          ports:
            - containerPort: 8081