apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: studyimg-node
  name: studyimg-node
spec:
  env:
    - name: CLOUDSDK_CONTAINER_CLUSTER
      value: "studyenv4-cluster"
    - name: CLOUDSDK_COMPUTE_ZONE
      value: "asia-northeast1-a"
  replicas: 3
  template:
    metadata:
      labels:
        name: studyimg-node
    spec:
      containers:
        - image: gcr.io/studyenv4/hello4:v1
          name: studyimg-node
          ports:
            - containerPort: 8081