apiVersion: v1
kind: Service
metadata:
  labels:
    name: studyimg-service
  name: studyimg-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ip-address"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: studyimg-node
  type: LoadBalancer